### ISSUE TITLE
Running with the nt database

### ISSUE THREAD

**Issue by aminards** [chrisgulvik/De-MetaST#1]
If I understand the paper correctly, the program converts the reference database to binary for each input primer set.  I have a use case to use the nt database as my reference which is huge.  It is taking a very long time with this as my reference and using 44 input primer sets.  

Can the reference database be converted one time and then queried for each primer set?

**Comment by chrisgulvik** [comment]
Hey @aminards thanks for your interest.
**Yes**, you can put all 44 primer sets into the Primers.txt file to have it only convert once and query the nt database.

The CAMERA webpage no longer exists to grab the nt.fasta so you might have to use `blastdbcmd` to create the file from NCBI downloaded nt.##.tar.gz files. At the time, CAMERA had each sequence entry as a single line so this program expects that format. Now that linewraps are more common, if you get your FastA in that format, you'll have to remove those before searching with this binary to get matches/amplicons.

**Comment by aminards** [comment]
Thanks for the tips.  I converted my nt database fasta to single line records (without line wraps) and things are moving much quicker now.

**Comment by chrisgulvik** [comment]
Thanks @aminards for the update. I'll close this ticket but if issues pop up feel free to create an issue.
